from transformers import pipeline

classifier = pipeline(task='sentiment-analysis', model='distilbert/distilbert-base-uncased-finetuned-sst-2-english')
result = classifier("I believe this movie should be rated 5-6 stars. Cooper had the ability to communicate with the past, he just can't tell NASA or his daughter the destination??? If Cooper gave the right information, they could avoid all the death and sacrifice. Mankind from the future could control gravity, and space time, and they failed to gave solution to blight???? When Cooper returned to the space station, he could share all his adventure stories, so future generations learnt his adventure, and in time, when they have the scientific ability, they could pass this information to Cooper in the first place or even people from even earlier. It's a paradox. Nolan tried to be scientifically correct. Cooper gave his daughter a mechanical Hamilton watch. I believe everyone knows how a mechanical watch, it is driven by springs and gears. A mechanical watch's movement direction won't be changed permanently by gravity. Gravity would slow down the watch, but when gravitational influence were gone, the movement should go back to normal, so there is no way, Cooper could use gravitational force to 'encode' a message into the mechanical watch because the hand of the watch wouldn't stay 'jumpy': moving back and foreth. He would have better luck using gravity to leave message on the floor. The whole 'watch' narrative was a big mistake. Cooper loved his daughter, okay, but what about the other kid? He acted as if he only had one kid. That's just weird. It is a good movie, black hole, wormhole stuff are easy to understand, but when you really put your brain to it, you see plot holes. Entertaining but this movie is actually quite stupid.")
print(result)

#classifier_summary = pipeline(task='summarization', model='t5-small')
#result = classifier_summary("I believe this movie should be rated 5-6 stars. Cooper had the ability to communicate with the past, he just can't tell NASA or his daughter the destination??? If Cooper gave the right information, they could avoid all the death and sacrifice. Mankind from the future could control gravity, and space time, and they failed to gave solution to blight???? When Cooper returned to the space station, he could share all his adventure stories, so future generations learnt his adventure, and in time, when they have the scientific ability, they could pass this information to Cooper in the first place or even people from even earlier. It's a paradox. Nolan tried to be scientifically correct. Cooper gave his daughter a mechanical Hamilton watch. I believe everyone knows how a mechanical watch, it is driven by springs and gears. A mechanical watch's movement direction won't be changed permanently by gravity. Gravity would slow down the watch, but when gravitational influence were gone, the movement should go back to normal, so there is no way, Cooper could use gravitational force to 'encode' a message into the mechanical watch because the hand of the watch wouldn't stay 'jumpy': moving back and foreth. He would have better luck using gravity to leave message on the floor. The whole 'watch' narrative was a big mistake. Cooper loved his daughter, okay, but what about the other kid? He acted as if he only had one kid. That's just weird. It is a good movie, black hole, wormhole stuff are easy to understand, but when you really put your brain to it, you see plot holes. Entertaining but this movie is actually quite stupid.")
#print(result)

#oracle = pipeline(model="deepset/roberta-base-squad2")
#result = oracle(question="what is my name ?", context="My name is Wolfgang and I live in Berlin")
#print(result)