CREATE DATABASE IF NOT EXISTS cineclub; -- create db if not exist

USE cineclub; -- use it

CREATE TABLE IF NOT EXISTS movies (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    poster VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    longdescription TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS actors (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    photo VARCHAR(255) NOT NULL,
    actorDescription TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_actor (
    movie_id INT NOT NULL,
    actor_id INT NOT NULL,
    PRIMARY KEY (movie_id, actor_id),
    FOREIGN KEY (movie_id) REFERENCES movies(id) ON DELETE CASCADE,
    FOREIGN KEY (actor_id) REFERENCES actors(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL, 
  password VARCHAR(255) NOT NULL
);


INSERT INTO movies (title, poster, description, longdescription) VALUES 
("Star Wars", "../assets/starwars.png", "In a galaxy far, far away...", "The Clone Wars rage across the galaxy as the Jedi struggle to maintain peace. Anakin Skywalker, a promising young Jedi Knight, is haunted by visions of his wife Padmé Amidala's impending death. Meanwhile, the enigmatic Chancellor Palpatine, secretly the dark lord of the Sith, Darth Sidious, manipulates Anakin's fears and insecurities."),
("Harry Potter and the philosopher stone", "../assets/hp1.jpg", "Harry Potter learns that he is a wizard and go for a journey to Hogwarts", "Harry Potter, an ordinary boy living a miserable life with his aunt, uncle, and cousin, discovers on his eleventh birthday that he is a wizard. He receives a letter of acceptance to Hogwarts School of Witchcraft and Wizardry and embarks on a magical journey. At Hogwarts, Harry makes friends with Ron Weasley and Hermione Granger. Together, they navigate the challenges of wizarding life, from learning spells and potions to playing Quidditch. Harry also learns about his tragic past, involving the dark wizard Lord Voldemort, who killed his parents. As the school year progresses, a mysterious force threatens the safety of Hogwarts. A powerful artifact, the Philosopher's Stone, is hidden within the school, and Voldemort seeks to use it to regain his power. Harry, Ron, and Hermione, along with their mentor, Professor Dumbledore, must protect the stone and confront the darkness that lurks within the castle walls."),
("Joker", "../assets/joker.png", "A gritty, psychological thriller set in a decaying Gotham City", "Joker is a psychological thriller that delves into the descent of Arthur Fleck, a troubled and marginalized individual living in Gotham City. As a failed stand-up comedian, Arthur struggles with mental illness and societal neglect. His condition worsens as he encounters violence and indifference, leading to a series of tragic events. As Arthur's mental state deteriorates, he embraces a darker persona inspired by the Joker, a notorious comic book villain. His actions spark a wave of chaos and violence in the city, culminating in a shocking climax that challenges the line between hero and villain. The film explores themes of mental illness, societal injustice, and the corrosive effects of isolation."),
("Parasite", "../assets/parasite.jpg", "A darkly comedic thriller, Parasite follows the impoverished Kim family as they slowly infiltrate the wealthy Park household through a series of calculated schemes", "The film 'Parasite' (2019) tells the story of the Kim family, a poor family living in a cramped basement apartment in Seoul. They are struggling to make ends meet with low-paying jobs. One day, their son, Ki-woo, is offered a job as a tutor for the wealthy Park family. Seeing an opportunity to improve their lives, the Kims devise a plan to infiltrate the Park household, one by one, taking on various roles under false pretenses. As the Kims become increasingly intertwined with the Park family, tensions rise and secrets are revealed. The film explores themes of class, wealth, and the blurred lines between the two families. A shocking twist unfolds, leading to a tragic climax that exposes the dark underbelly of their newfound prosperity."),
("Kung Fu Panda", "../assets/kfp1.png", "A clumsy panda named Po, who dreams of becoming a kung fu master, unexpectedly finds himself chosen as the Dragon Warrior", "Po, a clumsy panda with a love for noodles, dreams of becoming a kung fu master. Despite his unlikely appearance and lack of training, he is chosen as the Dragon Warrior, a legendary hero destined to save the Valley of Peace. Under the guidance of the wise Master Shifu and the Furious Five, Po must overcome his self-doubt and learn the ways of kung fu. He trains rigorously, mastering various martial arts styles, and discovers a hidden strength within himself. When the evil snow leopard Tai Lung escapes from prison and threatens the valley, Po must face his greatest challenge."),
("Le Comte de Monte-Cristo", "../assets/comte.png", "Edmond Dantès, a hopeful young sailor, is unjustly accused of treason on the eve of his wedding", "Edmond Dantès, a young and promising sailor, is falsely accused of treason on his wedding day. Betrayed by his friends, he is imprisoned in the infamous Château d'If. After years of unjust confinement, he escapes and inherits a vast fortune, transforming himself into the enigmatic Count of Monte Cristo. Driven by a thirst for vengeance, the Count meticulously plots his revenge against those who wronged him: Fernand Mondego, the ambitious man who coveted his fiancée; Gérard de Villefort, the corrupt prosecutor; and Danglars, the envious banker. As the Count weaves his intricate web of deceit and manipulation, he exposes the true nature of his enemies and brings them to justice. However, his pursuit of revenge also takes a toll on his own soul, forcing him to confront the consequences of his actions and the true meaning of justice.");

INSERT INTO actors (name, photo, actorDescription) VALUES
("Hayden Christensen", "../assets/actors/hc.png", "Hayden Christensen is a Canadian actor best known for his iconic portrayal of Anakin Skywalker and Darth Vader in the Star Wars prequel trilogy. Born on April 19, 1981, in Vancouver, Canada, Christensen's acting career began in his early teens with roles on Canadian television. 1  He gained international recognition for his performance in Star Wars: Episode II - Attack of the Clones and Star Wars: Episode III - Revenge of the Sith. 2  Beyond Star Wars, Christensen has appeared in films such as The Virgin Suicides, Life as a House, and Shattered Glass. 3  In recent years, he has reprised his role as Darth Vader in the Disney+ series Obi-Wan Kenobi and Ahsoka."),
("Ewan McGregor", "../assets/actors/ewan.png", "Ewan McGregor is a renowned Scottish actor, known for his versatility and captivating performances. Born on March 31, 1971, in Perth, Scotland, McGregor gained international recognition for his portrayal of Obi-Wan Kenobi in the Star Wars prequel trilogy. His career has been marked by diverse roles in critically acclaimed films such as Trainspotting, Moulin Rouge!, and Fargo. Beyond acting, McGregor is also a talented musician and has ventured into directing with films like American Pastoral. His dedication to his craft and his ability to embody a wide range of characters have solidified his status as one of the most respected actors of his generation."),
("Samuel L. Jackson", "../assets/actors/samueljackson.png", "Samuel L. Jackson, one of the most recognizable and prolific actors of his generation, has left an indelible mark on Hollywood. Born on December 21, 1948, in Washington, D.C., Jackson's journey to stardom was marked by a unique blend of talent, charisma, and a distinctive style. After studying at Morehouse College, Jackson's early career involved stage acting and smaller film roles. His breakthrough came in the 1990s with iconic performances in films like 'Pulp Fiction,' 'Jurassic Park,' and 'Die Hard with a Vengeance.' His collaborations with directors like Quentin Tarantino solidified his status as a leading man. Jackson's versatility is evident in his diverse roles, ranging from intense and gritty characters to charismatic and humorous ones. He has appeared in numerous blockbuster franchises, including 'Star Wars' and the Marvel Cinematic Universe. His distinctive voice and memorable quotes have become synonymous with his on-screen persona. Beyond his acting career, Jackson is also a vocal advocate for social justice and has used his platform to raise awareness about important issues. His impact on popular culture is undeniable, and his legacy as one of the greatest actors of all time is firmly established."),
("Natalie Portman", "../assets/actors/natalieportman.png", "Natalie Portman, born Natalie Hershlag on June 9, 1981, in Jerusalem, Israel, is a renowned actress, producer, and director. Her career has spanned decades, marked by both critically acclaimed performances and blockbuster roles. Portman's breakthrough came in 1994 with her role in the French film Léon: The Professional. She gained international recognition for portraying Queen Padmé Amidala in the Star Wars prequel trilogy. Her versatility as an actress is evident in her diverse roles, ranging from the intellectual and ambitious character in Closer to the tormented ballerina in Black Swan. In 2011, Portman won the Academy Award for Best Actress for her performance in Black Swan. She has also been nominated for multiple Golden Globe Awards and Screen Actors Guild Awards. Beyond her acting career, Portman is a dedicated advocate for animal rights and social justice. She is also a graduate of Harvard University, where she studied psychology."),
("Ian McDiarmid", "../assets/actors/iand.png", "Ian McDiarmid, a renowned Scottish actor and director, is best known for his iconic portrayal of Emperor Palpatine/Darth Sidious in the Star Wars saga. Born on August 11, 1944, in Carnoustie, Scotland, McDiarmid's career spans both stage and screen. Before his cinematic fame, McDiarmid established himself as a respected stage actor, performing in numerous Shakespearean plays and other theatrical productions. His talent and dedication earned him critical acclaim and several awards, including an Olivier Award and a Tony Award. While his role as the sinister Emperor Palpatine is undoubtedly his most recognizable, McDiarmid has also appeared in a variety of other films and television series, showcasing his versatility as an actor. His ability to embody complex and often villainous characters with nuance and depth has solidified his place as one of the most respected actors of his generation."),
("Christopher Lee", "../assets/actors/christopherlee.png", "Sir Christopher Lee, a towering figure in the world of cinema, was born on May 27, 1922, in Belgravia, London. With a career spanning over six decades, he became renowned for his deep, commanding voice and his ability to portray iconic villains. Lee's most famous roles include the enigmatic Count Dracula in numerous Hammer Horror films, the malevolent wizard Saruman in Peter Jackson's The Lord of the Rings trilogy, and the enigmatic Count Dooku in the Star Wars prequel trilogy. His imposing stature and intense presence made him a natural choice for such sinister characters. Beyond his villainous roles, Lee also showcased his versatility in a wide range of genres. He appeared in countless films, including The Man with the Golden Gun, The Wicker Man, and Sleepy Hollow. Knighted for his services to drama and charity in 2009, Sir Christopher Lee left an enduring legacy as one of the most iconic and respected actors of all time. He passed away on June 7, 2015, at the age of 93."),
("Daniel Radcliffe", "../assets/actors/danielr.png", "Daniel Radcliffe, born on July 23, 1989, in London, England, is an acclaimed actor best known for his iconic portrayal of the young wizard Harry Potter in the globally successful film series. Radcliffe's career skyrocketed at the age of 11 when he was cast as Harry Potter, a role that would define his early years. Throughout the decade-long series, he captivated audiences worldwide with his talent and dedication. However, Radcliffe's ambition extended beyond the magical world of Harry Potter. He sought to challenge himself with diverse roles, both on stage and screen. He has appeared in a range of films, including the psychological horror Horns and the comedy Swiss Army Man. Radcliffe has also made significant strides in theater, starring in productions like Equus, How to Succeed in Business Without Really Trying, and The Cripple of Inishmaan. His performances have earned him critical acclaim and prestigious awards, including a Tony Award. Beyond his acting career, Radcliffe is known for his philanthropic work and his openness about personal struggles, particularly with alcohol addiction. His journey of recovery and his willingness to share his experiences have inspired many."),
("Rupert Grint", "../assets/actors/rupertgrint.png", "Rupert Grint, born on August 24, 1988, in Harlow, England, is an English actor best known for his role as Ron Weasley in the Harry Potter film series. Cast at the age of 11, Grint portrayed the loyal and often comedic friend of Harry Potter throughout all eight films. Beyond his iconic role, Grint has continued to pursue acting, appearing in various films and television series. He has showcased his versatility, taking on diverse characters and exploring different genres. In recent years, Grint has also ventured into producing and has been involved in several projects. He remains a beloved figure in the entertainment industry, recognized for his talent, charm, and down-to-earth personality."),
("Emma Watson", "../assets/actors/emmawatson.png", "Emma Watson, born on April 15, 1990, in Paris, France, is an acclaimed English actress and activist. She rose to international fame for her portrayal of Hermione Granger in the Harry Potter film series, captivating audiences with her intelligence, wit, and loyalty. Beyond her iconic role, Watson has successfully transitioned into diverse roles, demonstrating her versatility as an actress. She has starred in films like 'The Perks of Being a Wallflower,' 'Beauty and the Beast,' and 'Little Women,' showcasing her range and talent. In addition to her acting career, Watson is a passionate advocate for gender equality and women's rights. She has served as a UN Women Goodwill Ambassador, promoting feminist ideals and inspiring young people around the world. Watson's influence extends beyond the screen, making her a role model for many and a powerful voice for positive change.");

INSERT INTO movie_actor (movie_id, actor_id) VALUES
(1, 1),
(1, 2),
(1, 3),
(1, 4),
(1, 5),
(1, 6),
(2, 7),
(2, 8),
(2, 9);

INSERT INTO users (username, password) VALUES
("admin", "admin");